"use client";

import { CheckCircle2, Sparkles, XCircle } from "lucide-react";

/**
 * What a learner sees after checking one answer.
 *
 * The verdict and the authored explanation are deterministic and are always
 * shown. Advisory AI greeting is an optional extra, labelled as a suggestion
 * with its provenance, and it is never required for the learner to continue.
 */
export function FeedbackPanel({
  check = null,
  explanation = null,
  explanationLoading = false,
  explanationUnavailable = false,
}) {
  if (!check) return null;

  const isCorrect = check.isCorrect;

  return (
    <section
      aria-live="polite"
      className={`flex flex-col gap-4 border-l-[3px] px-5 py-5 ${
        isCorrect
          ? "border-primary bg-primary/5"
          : "border-destructive bg-destructive/5"
      }`}
    >
      <div className="flex items-center gap-2.5">
        {isCorrect ? (
          <CheckCircle2 aria-hidden="true" className="size-5 shrink-0 text-primary" />
        ) : (
          <XCircle aria-hidden="true" className="size-5 shrink-0 text-destructive" />
        )}
        <h3 className={`text-base font-semibold ${isCorrect ? "text-primary" : "text-destructive"}`}>
          {isCorrect ? "Correct!" : "Not quite yet."}
        </h3>
      </div>

      <div className="flex flex-col gap-3 text-sm leading-relaxed text-foreground">
        {isCorrect && check.attemptsForQuestion > 1 && (
          <p className="text-muted-foreground">
            You got it on attempt {check.attemptsForQuestion}.
          </p>
        )}
        {check.feedback && <p>{check.feedback}</p>}
        {!isCorrect && (
          <p className="text-muted-foreground">
            Change your answer and check again, or come back to this one later.
          </p>
        )}
      </div>

      {!isCorrect && (explanation !== null || explanationLoading) && (
        <div className="border-t border-border/70 pt-4">
          <div className="flex items-start gap-3">
            <Sparkles aria-hidden="true" className="mt-0.5 size-4 shrink-0 text-muted-foreground" />
            <div className="flex flex-col gap-1">
              <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                AI suggestion
              </p>
              {explanationLoading ? (
                <p className="text-sm italic text-muted-foreground animate-pulse">
                  Thinking up a helpful explanation…
                </p>
              ) : (
                <>
                  <p className="text-sm leading-relaxed text-foreground">
                    {explanation.text}
                  </p>
                  <p className="text-xs text-muted-foreground">
                    Optional help, not a grade. {explanation.provider && `Generated by MathSmart AI (${explanation.model ?? "model"}).`}
                  </p>
                </>
              )}
            </div>
          </div>
        </div>
      )}

      {!isCorrect && explanation === null && !explanationLoading && explanationUnavailable && (
        <p className="border-t border-border/70 pt-4 text-xs text-muted-foreground">
          The optional AI explanation is unavailable right now. Your answer and
          score are not affected.
        </p>
      )}
    </section>
  );
}