"use client";

import { CheckCircle2, Sparkles, XCircle } from "lucide-react";

/**
 * What a learner sees after checking one answer.
 *
 * The verdict and the authored explanation are deterministic and are always
 * shown. Advisory AI wording is an optional extra, labelled as a suggestion
 * with its provenance, and it is never required for the learner to continue.
 *
 * Two things are announced and nothing else: the verdict, once, and the AI
 * wording, once it exists. They are announced from their own small regions
 * rather than from the panel, because a live region around the whole panel
 * announced the verdict, then the explanation, then the AI loading line, then
 * the AI text — four interruptions for one wrong answer, by which point a
 * learner using a screen reader had lost the one sentence that mattered. The
 * regions are rendered whether or not there is a verdict yet, since a live
 * region that appears together with its text is not reliably read at all.
 */
export function FeedbackPanel({
  check = null,
  explanation = null,
  explanationLoading = false,
  explanationUnavailable = false,
}) {
  const isCorrect = check?.isCorrect === true;

  /** The verdict as one sentence, which is what gets announced. */
  const spokenVerdict = !check
    ? ""
    : isCorrect
      ? "Correct."
      : "Not quite yet. Change your answer and check again, or come back to it later.";

  /** Announced only once it has arrived; the waiting line is not announced. */
  const spokenAdvice =
    check && !isCorrect && explanation?.text
      ? `Optional AI suggestion: ${explanation.text}`
      : "";

  return (
    <>
      <p aria-live="polite" className="sr-only">
        {spokenVerdict}
      </p>
      <p aria-live="polite" className="sr-only">
        {spokenAdvice}
      </p>

      {check && (
        <section
          aria-label="Answer feedback"
          className={`flex flex-col gap-4 border-l-[3px] px-5 py-5 ${
            isCorrect ? "border-primary bg-primary/5" : "border-destructive bg-destructive/5"
          }`}
        >
          <div className="flex items-center gap-2.5">
            {isCorrect ? (
              <CheckCircle2 aria-hidden="true" className="size-5 shrink-0 text-primary" />
            ) : (
              <XCircle aria-hidden="true" className="size-5 shrink-0 text-destructive" />
            )}
            <h3
              className={`text-base font-semibold ${
                isCorrect ? "text-primary" : "text-destructive"
              }`}
            >
              {isCorrect ? "Correct!" : "Not quite yet."}
            </h3>
          </div>

          <div className="flex flex-col gap-3 text-sm leading-relaxed text-foreground">
            {isCorrect && check.attemptsForQuestion > 1 && (
              <p className="text-muted-foreground">
                You got it on attempt {check.attemptsForQuestion}.
              </p>
            )}
            {check.feedback && <p>{check.feedback}</p>}
            {!isCorrect && (
              <p className="text-muted-foreground">
                Change your answer and check again, or come back to this one later.
              </p>
            )}
          </div>

          {!isCorrect && (explanation !== null || explanationLoading) && (
            <div className="border-t border-border/70 pt-4">
              <div className="flex items-start gap-3">
                <Sparkles
                  aria-hidden="true"
                  className="mt-0.5 size-4 shrink-0 text-muted-foreground"
                />
                <div className="flex flex-col gap-1">
                  <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                    AI suggestion
                  </p>
                  {explanationLoading ? (
                    <p className="text-sm italic text-muted-foreground animate-pulse motion-reduce:animate-none">
                      Thinking up a helpful explanation…
                    </p>
                  ) : (
                    <>
                      <p className="text-sm leading-relaxed text-foreground">
                        {explanation.text}
                      </p>
                      <p className="text-xs text-muted-foreground">
                        Optional help, not a grade.{" "}
                        {explanation.provider &&
                          `Generated by MathSmart AI (${explanation.model ?? "model"}).`}
                      </p>
                    </>
                  )}
                </div>
              </div>
            </div>
          )}

          {!isCorrect && explanation === null && !explanationLoading && explanationUnavailable && (
            <p className="border-t border-border/70 pt-4 text-xs text-muted-foreground">
              The optional AI explanation is unavailable right now. Your answer and score are not
              affected.
            </p>
          )}
        </section>
      )}
    </>
  );
}
